SRC_DIR = File.dirname(__FILE__)

task :clean do
  makefile = File.join(SRC_DIR, 'Makefile')

  if File.exists? makefile
    sh 'make clean'
    sh 'rm %s' % makefile
  end
end

task :build => :clean do
  sh 'ruby extconf.rb'
  sh 'make'
end

task :test do
  sh 'testrb %s' % Dir[File.join(SRC_DIR, 'test/test_*.rb')].join(' ')
end

task :default => [:build, :test]
