SRC_DIR = File.dirname(__FILE__)
ENV['RUBY_ROOT'] ||= File.dirname(File.dirname(`type ruby`))

desc 'Clean the build artifacts (eg. ripper.so)'
task :clean do
  makefile = File.join(SRC_DIR, 'Makefile')

  if File.exists? makefile
    sh 'make clean'
    sh 'rm %s' % makefile
  end
end

desc 'Generate ripper.so'
task :build => :clean do
  sh 'ruby extconf.rb'
  sh 'make'
end

desc 'Test the generated ripper.so'
task :test do
  sh 'testrb %s' % Dir[File.join(SRC_DIR, 'test/ripper/test_*.rb')].join(' ')
end

task :default => [:build, :test]
